version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://192.168.7.221:3808/admin}
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped 