export const DS_MA_KET_QUA: Record<string, string> = {
  '000': 'Thông tin chính xác',
  '001': 'Mã do BQP quản lý',
  '002': 'Mã do BCA quản lý',
  '003': 'Hết giá trị sử dụng, được cấp thẻ mới',
  '004': 'Còn giá trị sử dụng, được cấp thẻ mới',
  '010': 'Hết giá trị sử dụng',
  '051': 'Mã thẻ không đúng',
  '052': 'Mã tỉnh cấp thẻ không đúng',
  '053': 'Mã quyền lợi không đúng',
  '050': 'Không xác thực được thông tin',
  '060': 'Sai họ tên hoặc số CCCD',
  '061': 'Sai họ tên (đúng ký tự đầu)',
  '070': 'Sai ngày sinh',
  '100': 'Lỗi khi lấy dữ liệu sổ thẻ',
  '101': 'Lỗi server',
  '110': 'Đã thu hồi',
  '120': 'Đã báo giảm',
  '121': 'Đã báo giảm chuyển ngoại tỉnh',
  '122': 'Đã báo giảm chuyển nội tỉnh',
  '123': 'Đã báo giảm do tăng lại cùng đơn vị',
  '124': 'Đã báo giảm ngừng tham gia',
  '130': 'Trẻ em không xuất trình thẻ BHYT',
  '205': 'Lỗi sai định dạng tham số',
  '401': 'Lỗi xác thực tài khoản',
  '500': 'Lỗi máy chủ',
  '054': 'Số CCCD của cán bộ thực hiện tra cứu không tồn tại',
  '055': 'Họ và tên của cán bộ thực hiện tra cứu không khớp',
}

// Error code
export const ERROR_CODE = {
  '001': 'Mã do BQP quản lý',
  '002': 'Mã do BCA quản lý',
  '051': 'Mã thẻ không đúng',
  '050': 'Không xác thực được thông tin',
  '060': 'Sai họ tên hoặc số CCCD',
  '061': 'Sai họ tên (đúng ký tự đầu)',
  '070': 'Sai ngày sinh',
  '101': 'Lỗi server',
  '205': 'Lỗi sai định dạng tham số',
  '401': 'Lỗi xác thực tài khoản',
  '500': 'Lỗi máy chủ',
  '054': 'Số CCCD của cán bộ thực hiện tra cứu không tồn tại',
  '055': 'Họ và tên của cán bộ thực hiện tra cứu không khớp',
}